// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Frames         string
	Games          string
	GooseDBVersion string
	Throws         string
	UserTokens     string
	Users          string
}{
	Frames:         "frames",
	Games:          "games",
	GooseDBVersion: "goose_db_version",
	Throws:         "throws",
	UserTokens:     "user_tokens",
	Users:          "users",
}
