// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFrames(t *testing.T) {
	t.Parallel()

	query := Frames()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFramesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFramesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Frames().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFramesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FrameSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFramesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FrameExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Frame exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FrameExists to return true, but got false.")
	}
}

func testFramesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	frameFound, err := FindFrame(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if frameFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFramesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Frames().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFramesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Frames().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFramesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	frameOne := &Frame{}
	frameTwo := &Frame{}
	if err = randomize.Struct(seed, frameOne, frameDBTypes, false, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}
	if err = randomize.Struct(seed, frameTwo, frameDBTypes, false, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = frameOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = frameTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Frames().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFramesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	frameOne := &Frame{}
	frameTwo := &Frame{}
	if err = randomize.Struct(seed, frameOne, frameDBTypes, false, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}
	if err = randomize.Struct(seed, frameTwo, frameDBTypes, false, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = frameOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = frameTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func frameBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func frameAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Frame) error {
	*o = Frame{}
	return nil
}

func testFramesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Frame{}
	o := &Frame{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, frameDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Frame object: %s", err)
	}

	AddFrameHook(boil.BeforeInsertHook, frameBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	frameBeforeInsertHooks = []FrameHook{}

	AddFrameHook(boil.AfterInsertHook, frameAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	frameAfterInsertHooks = []FrameHook{}

	AddFrameHook(boil.AfterSelectHook, frameAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	frameAfterSelectHooks = []FrameHook{}

	AddFrameHook(boil.BeforeUpdateHook, frameBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	frameBeforeUpdateHooks = []FrameHook{}

	AddFrameHook(boil.AfterUpdateHook, frameAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	frameAfterUpdateHooks = []FrameHook{}

	AddFrameHook(boil.BeforeDeleteHook, frameBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	frameBeforeDeleteHooks = []FrameHook{}

	AddFrameHook(boil.AfterDeleteHook, frameAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	frameAfterDeleteHooks = []FrameHook{}

	AddFrameHook(boil.BeforeUpsertHook, frameBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	frameBeforeUpsertHooks = []FrameHook{}

	AddFrameHook(boil.AfterUpsertHook, frameAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	frameAfterUpsertHooks = []FrameHook{}
}

func testFramesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFramesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(frameColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFrameToManyThrows(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Frame
	var b, c Throw

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, throwDBTypes, false, throwColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, throwDBTypes, false, throwColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.FrameID = a.ID
	c.FrameID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Throws().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.FrameID == b.FrameID {
			bFound = true
		}
		if v.FrameID == c.FrameID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := FrameSlice{&a}
	if err = a.L.LoadThrows(ctx, tx, false, (*[]*Frame)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Throws); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Throws = nil
	if err = a.L.LoadThrows(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Throws); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testFrameToManyAddOpThrows(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Frame
	var b, c, d, e Throw

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, frameDBTypes, false, strmangle.SetComplement(framePrimaryKeyColumns, frameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Throw{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, throwDBTypes, false, strmangle.SetComplement(throwPrimaryKeyColumns, throwColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Throw{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddThrows(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.FrameID {
			t.Error("foreign key was wrong value", a.ID, first.FrameID)
		}
		if a.ID != second.FrameID {
			t.Error("foreign key was wrong value", a.ID, second.FrameID)
		}

		if first.R.Frame != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Frame != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Throws[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Throws[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Throws().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testFrameToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Frame
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, frameDBTypes, false, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := FrameSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Frame)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testFrameToOneGameUsingGame(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Frame
	var foreign Game

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, frameDBTypes, false, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, gameDBTypes, false, gameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Game struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.GameID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Game().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddGameHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Game) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := FrameSlice{&local}
	if err = local.L.LoadGame(ctx, tx, false, (*[]*Frame)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Game == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Game = nil
	if err = local.L.LoadGame(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Game == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testFrameToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Frame
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, frameDBTypes, false, strmangle.SetComplement(framePrimaryKeyColumns, frameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Frames[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}
func testFrameToOneSetOpGameUsingGame(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Frame
	var b, c Game

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, frameDBTypes, false, strmangle.SetComplement(framePrimaryKeyColumns, frameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, gameDBTypes, false, strmangle.SetComplement(gamePrimaryKeyColumns, gameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, gameDBTypes, false, strmangle.SetComplement(gamePrimaryKeyColumns, gameColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Game{&b, &c} {
		err = a.SetGame(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Game != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Frames[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.GameID != x.ID {
			t.Error("foreign key was wrong value", a.GameID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.GameID))
		reflect.Indirect(reflect.ValueOf(&a.GameID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.GameID != x.ID {
			t.Error("foreign key was wrong value", a.GameID, x.ID)
		}
	}
}

func testFramesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFramesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FrameSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFramesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Frames().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	frameDBTypes = map[string]string{`ID`: `int`, `UserID`: `int`, `GameID`: `int`, `FrameCount`: `decimal`, `FrameScore`: `int`, `StrikeFlag`: `tinyint`, `SpareFlag`: `tinyint`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedFLG`: `tinyint`, `DeletedAt`: `datetime`}
	_            = bytes.MinRead
)

func testFramesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(framePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(frameAllColumns) == len(framePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, frameDBTypes, true, framePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFramesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(frameAllColumns) == len(framePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Frame{}
	if err = randomize.Struct(seed, o, frameDBTypes, true, frameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, frameDBTypes, true, framePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(frameAllColumns, framePrimaryKeyColumns) {
		fields = frameAllColumns
	} else {
		fields = strmangle.SetComplement(
			frameAllColumns,
			framePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FrameSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFramesUpsert(t *testing.T) {
	t.Parallel()

	if len(frameAllColumns) == len(framePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLFrameUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Frame{}
	if err = randomize.Struct(seed, &o, frameDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Frame: %s", err)
	}

	count, err := Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, frameDBTypes, false, framePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Frame struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Frame: %s", err)
	}

	count, err = Frames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
