// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Frames", testFramesUpsert)

	t.Run("Games", testGamesUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Throws", testThrowsUpsert)

	t.Run("UserTokens", testUserTokensUpsert)

	t.Run("Users", testUsersUpsert)
}
